version: "3.3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - telegram/.production.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/script:/docker-entrypoint-initdb.d

  telegram:
    container_name: telegram
    hostname: telegram
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres

volumes:
  postgres_data:
